version: "3.3"

services:
  database: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: db_postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=tws
      - POSTGRES_PASSWORD=wlu@2341
      - POSTGRES_DB=tranportadora
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: transportadora
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database



volumes:
  pgdata:
    driver: local